import { Inter } from "next/font/google";
import "./globals.css";
import { WalletContextProvider } from "@/context/wallet";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WalletContextProvider>
        <body className={inter.className}>
          <Header />
            {children}
          <Footer />
        </body>
      </WalletContextProvider>
    </html>
  );
}