import { Inter } from "next/font/google";
import "./globals.css";
import { WalletContextProvider } from "@/context/wallet";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "XDC NFT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WalletContextProvider>
        <body className={inter.className}>
          <Header />
          <ToastContainer position="top-left" autoClose={3000} />
            {children}
          <Footer />
        </body>
      </WalletContextProvider>
    </html>
  );
}
